import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="min-h-full flex flex-col">

<nav
  className="w-full text-white border-b p-4"
  style={{ backgroundColor: "#2F4F6F"  }}
>
  <div className="w-full flex items-center justify-between">
    
    {/* Left */}
    <div className="w-1/3">
      <h1 className="font-bold text-lg ml-6">Caribou Accounting</h1>
    </div>

    {/* Middle */}
    <div className="w-1/3 flex justify-center gap-8">
      <a href="/">Home</a>
      <a href="/about">About</a>
      <a href="/services">Services</a>
      <a href="/pricing">Pricing</a>
      <a href="/getstarted">Get Started</a>
    </div>

    {/* Right placeholder */}
    <div className="w-1/3"></div>

  </div>
</nav>
  {children}

</body>
    </html>
  );
}

